site_name: POLAR
site_description: POint cloud LAtent Registration.
site_author: Luc Vedrenne
site_url: https://pypolar.github.io/polar/
repo_url: https://github.com/pypolar/polar.git
repo_name: pypolar/polar
# No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's
# impossible for them all to be accurate.
edit_uri: ""
strict: true  # Don't allow warnings during the build process

watch:
    - polar

# _______________________________________________________________________________________________ #

theme:
    name: material
    features:
        # - navigation.tabs
        - navigation.sections # Sections are included in the navigation on the left.
        - navigation.expand
        - navigation.instant # XHR dispatching without full page reloading
        - navigation.tracking # Update URL with active anchor
        - navigation.top # Back to top button when scrolling down
        # Table of contents is integrated on the left; does not appear separately on the right.
        # - toc.integrate  
        - toc.follow  # active anchor is always visible
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to
        # light mode as (a) it looks more professional, and (b) is more obvious about the fact that
        # it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/circle-opacity"  # Equinox logo in top left
    favicon: "_static/favicon.png"
    # Bellow is commented out because it is not required in this particular project.
    # custom_dir: "docs/_overrides"  # Overriding part of the HTML


# _______________________________________________________________________________________________ #

extra_javascript: 
    # The below three make MathJax work, see:
    # https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# _______________________________________________________________________________________________ #

extra_css:
    - _static/custom_css.css


# _______________________________________________________________________________________________ #

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - codehilite  
    - toc:
        title: On this page
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4


# _______________________________________________________________________________________________ #

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    # Bellow is commented out because it is not required in this particular project.
    # - include_exclude_files:
    #     include:
    #         - ".htaccess"
    #     exclude:
    #         - "_overrides"
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()

                selection:
                    inherited_members: true  # Allow looking up inherited methods
                options:
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: false  # display "module.function" not just "function"
                    show_if_no_docstring: false
                    show_signature_annotations: true
                    show_source: true  # don't include source code
                    # Order methods according to their order of definition in the source code,
                    # not alphabetical order.
                    members_order: source  
                    heading_level: 4
                    # -------------------
                    docstring_section_style: list
                    docstring_options:
                        ignore_init_summary: true
                    merge_init_into_class: true


# _______________________________________________________________________________________________ #

nav:
    - 'index.md'
    - Examples:
        - Introduction: 'examples/examples.ipynb'
    - Full API:
        - Core:
            - POLAR: 'api/polar/polar.md'
            - AE: 'api/polar/ae.md'
            - SO(3): 'api/polar/so3.md'
        - Data:
            - ModelNet40 Loaders: 'api/data/dataloaders.md'
            - Transforms: 
                - Core: 'api/data/core.md'
                - Functionals: 'api/data/functionals.md'
                - Classes: 'api/data/transforms.md'
            - Sample dataset: 'api/data/sample_data.md'
        - Train: 'api/train.md'
        - Visualization: 'api/visualize.md'
