name = "AUGMENTED_V1"
rootdir = "modelnet"
shuffle = true
num_points = 1024
max_angle = 180
max_trans = 0.0
sigma = 0.05
min_scale = 0.8
keep_ratio = 0.8
p = 0.5
batch_size = 128
num_workers = 4
first_stage_widths = [ 64, 64,]
second_stage_widths = [ 64, 128, 1024,]
decoder_widths = [ 1024, 1024,]
dropout = 0.1
lr = 0.001
norm = 2
resume_optimizer = false
freeze_decoder = false
epochs = 250
log_dir = "logs/ae"
